input:
  csv:
    paths:
      - ./your_file.csv
    parse_header_row: true

pipeline:
  processors:
    - mapping: |
        root = {}
        this.each((value, key) -> {
          root = root.set(key, value)
        })
processors:
  - mapping: |
      root = {}
      meta header_keys = @header
      meta header_keys.each(key -> {
        let value = this[key]
        root = root.set(key, value)
      })        

output:
  file:
    path: ./output/transformed_data.json
    codec: json_lines
